# Generated by Django 5.2.7 on 2025-11-11 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('brand_primary', models.CharField(default='#2F6AFD', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('everyone', models.BooleanField(default=True, help_text='If true, visible to all; if false, restrict by departments.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('review_interval_days', models.PositiveIntegerField(default=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='documents', to='docs.department')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docs.organization')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='docs.organization'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subcollections', models.ManyToManyField(blank=True, related_name='parent_collection', to='docs.collection')),
                ('documents', models.ManyToManyField(blank=True, related_name='collections', to='docs.document')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='docs.organization')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('org', 'name'), ('org', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=160)),
                ('url', models.URLField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='docs.document')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='docs.organization')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('header', models.CharField(max_length=160)),
                ('body_md', models.TextField(blank=True, help_text='Markdown content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='docs.document')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='docs.organization')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('link_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_by_tags', to='docs.collection')),
                ('link_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_by_tags', to='docs.department')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_by_tags', to='docs.document')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='docs.organization')),
            ],
            options={
                'unique_together': {('org', 'name'), ('org', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='docs.tag'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('font_family', models.CharField(default='Inter, Segoe UI, Roboto, Arial, sans-serif', max_length=120)),
                ('base_font_size_px', models.PositiveIntegerField(default=16)),
                ('color_bg', models.CharField(default='#0f172a', max_length=16)),
                ('color_text', models.CharField(default='#94a3b8', max_length=16)),
                ('color_text_strong', models.CharField(default='#e2e8f0', max_length=16)),
                ('color_accent', models.CharField(default='#2dd4bf', max_length=16)),
                ('header_html', models.TextField(blank=True)),
                ('footer_html', models.TextField(blank=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='docs.organization')),
            ],
            options={
                'unique_together': {('org', 'name'), ('org', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docs.template'),
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('external', 'External Link'), ('document', 'Single Document'), ('department', 'Department'), ('collection', 'Collection')], max_length=20)),
                ('href', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiles', to='docs.collection')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiles', to='docs.department')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiles', to='docs.document')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='docs.organization')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='docs.organization')),
            ],
            options={
                'unique_together': {('org', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('org', 'name'), ('org', 'slug')},
        ),
        migrations.CreateModel(
            name='RequirementSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content_md', models.TextField(help_text='Markdown content')),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='docs.organization')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='docs.tag')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'unique_together': {('tag', 'title')},
            },
        ),
    ]
