# Generated by Django 5.2.7 on 2025-11-13 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requirementsnippet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resourcelink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tile',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='requirementsnippet',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='document',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='document',
            name='review_interval_days',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='resourcelink',
            name='order',
        ),
        migrations.RemoveField(
            model_name='resourcelink',
            name='org',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
        migrations.RemoveField(
            model_name='section',
            name='org',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='icon',
        ),
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=160),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subcollections',
            field=models.ManyToManyField(blank=True, related_name='parent_collections', to='docs.collection'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=32),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='brand_primary',
            field=models.CharField(default='#3a7bfa', help_text='Hex color like #3a7bfa', max_length=7),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='requirementsnippet',
            name='content_md',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requirementsnippet',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_snippets', to='docs.organization'),
        ),
        migrations.AlterField(
            model_name='requirementsnippet',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requirementsnippet',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_snippets', to='docs.tag'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='body_md',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='header',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='link_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tags', to='docs.collection'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='link_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tags', to='docs.department'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tags', to='docs.document'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=160),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='tile',
            name='kind',
            field=models.CharField(choices=[('document', 'Document'), ('department', 'Department'), ('collection', 'Collection'), ('url', 'URL')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['org', 'slug'], name='docs_collec_org_id_8e17ae_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['org', 'name'], name='docs_collec_org_id_bca551_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['org', 'order'], name='docs_collec_org_id_e7be92_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['org', 'slug'], name='docs_depart_org_id_269d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['org', 'name'], name='docs_depart_org_id_5648b8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['org', 'slug'], name='docs_docume_org_id_c96a47_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['org', 'title'], name='docs_docume_org_id_52eb29_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['org', 'status'], name='docs_docume_org_id_d75663_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['org', 'updated_at'], name='docs_docume_org_id_1b4b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['org', 'role'], name='docs_member_org_id_0485d6_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user'], name='docs_member_user_id_9f3e92_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='docs_organi_slug_6a624a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='docs_organi_name_724d12_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementsnippet',
            index=models.Index(fields=['org', 'priority'], name='docs_requir_org_id_b6630a_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementsnippet',
            index=models.Index(fields=['org', 'title'], name='docs_requir_org_id_6a761f_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelink',
            index=models.Index(fields=['document', 'id'], name='docs_resour_documen_535c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelink',
            index=models.Index(fields=['title'], name='docs_resour_title_d64eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['document', 'id'], name='docs_sectio_documen_a3353a_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['org', 'slug'], name='docs_tag_org_id_14d67f_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['org', 'name'], name='docs_tag_org_id_6d1416_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['org', 'name'], name='docs_templa_org_id_fb8c30_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['org', 'slug'], name='docs_templa_org_id_9b5516_idx'),
        ),
        migrations.AddIndex(
            model_name='tile',
            index=models.Index(fields=['org', 'is_active', 'order'], name='docs_tile_org_id_ce977a_idx'),
        ),
        migrations.AddIndex(
            model_name='tile',
            index=models.Index(fields=['org', 'kind'], name='docs_tile_org_id_514b91_idx'),
        ),
        migrations.AddIndex(
            model_name='tile',
            index=models.Index(fields=['org', 'title'], name='docs_tile_org_id_352a3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('org', 'slug'), name='uniq_collection_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('org', 'slug'), name='uniq_department_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False), models.Q(('slug', ''), _negated=True)), fields=('org', 'slug'), name='uniq_document_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'org'), name='uniq_membership_user_org'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('org', 'slug'), name='uniq_tag_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False), models.Q(('slug', ''), _negated=True)), fields=('org', 'slug'), name='uniq_template_org_slug'),
        ),
        migrations.RemoveField(
            model_name='requirementsnippet',
            name='active',
        ),
        migrations.RemoveField(
            model_name='template',
            name='base_font_size_px',
        ),
        migrations.RemoveField(
            model_name='template',
            name='color_accent',
        ),
        migrations.RemoveField(
            model_name='template',
            name='color_bg',
        ),
        migrations.RemoveField(
            model_name='template',
            name='color_text',
        ),
        migrations.RemoveField(
            model_name='template',
            name='color_text_strong',
        ),
        migrations.RemoveField(
            model_name='template',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='template',
            name='footer_html',
        ),
        migrations.RemoveField(
            model_name='template',
            name='header_html',
        ),
    ]
