# Generated by Django 5.2.7 on 2025-11-16 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_section_options_section_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=16)),
                ('everyone', models.BooleanField(default=False)),
                ('tag_ids', models.JSONField(blank=True, default=list)),
                ('collection_ids', models.JSONField(blank=True, default=list)),
                ('department_ids', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='docs.document')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='docs.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', 'created_at'], name='docs_docume_org_id_0ff7f8_idx'), models.Index(fields=['document', 'created_at'], name='docs_docume_documen_b15ae3_idx')],
            },
        ),
    ]
