# Generated by Django 5.2.7 on 2025-11-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='subcollections',
            field=models.ManyToManyField(blank=True, related_name='parent_collection', to='docs.collection'),
        ),
    ]
