# Generated by Django 5.2.7 on 2025-11-08 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_collection_subcollections'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='link_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_by_tags', to='docs.collection'),
        ),
        migrations.AddField(
            model_name='tag',
            name='link_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_by_tags', to='docs.department'),
        ),
    ]
